name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          flake8 scripts/ --max-line-length=120 --ignore=E501,W503 --count --statistics

      - name: Verify dataset integrity
        run: |
          python -c "
          import pandas as pd
          df = pd.read_csv('data/gym_members_exercise_tracking.csv')
          assert len(df) == 973, f'Expected 973 rows, got {len(df)}'
          assert df.isnull().sum().sum() == 0, 'Dataset contains null values'
          print(f'Dataset OK: {df.shape[0]} rows, {df.shape[1]} columns, 0 nulls')
          "

      - name: Run visuals generation
        run: |
          python scripts/generate_visuals.py

      - name: Upload visuals as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-visuals-py${{ matrix.python-version }}
          path: visuals/
          retention-days: 7
